PetLivesMatter/PetLivesMatter/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from django.urls import include
from PetRegistry import views
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

from PetRegistry.views import (
    home_screen_view,
    pet_detail_view
)

from account.views import(
    signup_view, user_detail,
)

# clean up unnecessary comments and old code

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_screen_view, name='home'),
    path('about/', views.about, name='about'),
    path('donate/', views.donate, name='donate'),
    path('pet_register/', views.pet_register_view, name="pet_register"),
    path('my_pets/', views.MyPetListView.as_view(), name="my_pets"),
    path('user_detail/', user_detail, name='user_detail'),
    path('pet/<int:pk>', pet_detail_view, name='pet_detail'),
    path('signup/', signup_view, name='signup'),
    path('missing_pets/', views.MissingPetsView.as_view(), name="missing_pets"),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

# Add Django site authentication urls (for login, logout, password management)

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),

]

PetLivesMatter/PetRegistry/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from django.urls import include
from PetRegistry import views
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

from PetRegistry.views import (
    home_screen_view,
)

urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += [
    path('', home_screen_view, name='home'),
]

urlpatterns += [
    path('', RedirectView.as_view(url='/home/')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

#Add Django site authentication urls (for login, logout, password management)

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),

]

PetLivesMatter/PetRegistry/models.py
from django.db import models
from django.conf import settings

# Create your models here.

class Pet(models.Model):

    SPECIES_CHOICES =(
        ("Dog",
            (
                ("Mutt","Mutt"),
                ("Dalmatian","Dalmatian"),
                ("German Shepherd","German Shepherd"),
                ("Corgie","Corgie"),
                ("Beagle","Beagle"),
                ("Husky","Husky"),
            )
        ),
        ("Cat",
            (
                ("Housecat","Housecat"),
                ("Sphynx","Sphynx"),
                ("Siamese","Siamese"),
                ("Bengal","Bengal"),
                ("Maine Coon","Maine Coon"),
                ("Ragdoll","Ragdoll"),
            )
        ),
        ("Parrot",
            (
                ("Cockatoo","Cockatoo"),
                ("Indian Ringneck","Indian Ringneck"),
                ("Macaw","Macaw"),
                ("Galah","Galah"),
                ("Cockatiel","Cockatiel"),
                ("Conure","Conure"),
            )
        ),
        ("Snake",
            (
                ("Anaconda","Anaconda"),
                ("Rattlesnake","Rattlesnake"),
                ("Cobra","Cobra"),
                ("Asp","Asp"),
                ("Python","Python"),
                ("Sea Snake","Sea Snake"),
            )
        ),
    )

    SEX_CHOICES = (("Female", "Female"),("Male","Male"))
    COLOUR_CHOICES = (("Brown","Brown"),("Black","Black"),("White","White"),
    ("Orange","Orange"),("Green","Green"),("Yellow","Yellow"),("Blue","Blue"))
    pet_name = models.CharField(max_length=30)
    species = models.CharField(max_length=20, choices=SPECIES_CHOICES)
    age = models.PositiveIntegerField()
    sex = models.CharField(max_length = 7, choices=SEX_CHOICES)
    colour = models.CharField(choices = COLOUR_CHOICES, max_length=10)
    eye_colour = models.CharField(choices = COLOUR_CHOICES, max_length=10)
    markings = models.CharField(max_length=250)
    missing = models.BooleanField(default = False)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)
    imagefile= models.FileField(upload_to='images/', null=True, verbose_name="")

    def __str__(self):
        return self.pet_name + ': ' + str(self.imagefile) + self.colour + ' ' + self.species

PetLivesMatter/PetRegistry/forms.py
from django import forms
from .models import Pet
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

# cleaned old code and tidied format

class PetForm(forms.ModelForm):
    class Meta:
        model = Pet
        fields = ('imagefile', 'pet_name', 'species', 'age', 'sex', 'colour','eye_colour','markings')

class MissingPetForm(forms.Form):
    Pet_missing = forms.BooleanField()

PetLivesMatter/PetRegistry/views.py
from django.shortcuts import render, redirect
from django.views import generic
from django.http import HttpResponse
from django.http import Http404
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from .forms import PetForm, MissingPetForm
from .models import Pet
from account.models import Account

# cleaned code and formatted

def home_screen_view(request):
    context = {}
    accounts = Account.objects.all()
    context['accounts'] = accounts
    return render(request, 'home.html', context)

def about(request):
    return render(request, 'about.html')

def donate(request):
    return render(request, 'donate.html')

def pet_register_view(request):
    lastimage= Pet.objects.last()
    imagefile= lastimage.imagefile
    form = PetForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        pet = form.save(commit=False)
        pet.owner = request.user
        pet.save()
        return redirect('my_pets')
    return render(request, 'pet_register.html', {'imagefile': imagefile, 'form': form})

class MissingPetsView(generic.ListView):
    model = Pet
    template_name = 'missing_pets.html'

class MyPetListView(generic.ListView):
    model = Pet
    template_name = 'my_pets.html'

def pet_detail_view(request, pk):
    try:
        pet = Pet.objects.get(id = pk)
        if pet.missing == True:
            form = MissingPetForm(request.POST or None, initial = {'Pet_missing' : 'True'})
        else:
            form = MissingPetForm(request.POST or None, initial = {'Pet_missing' : 'False'})

    except Pet.DoesNotExist:
        raise Http404('pet not found')

    return render(request, 'pet_detail.html', {'pet': pet, 'form': form})

PetLivesMatter/PetRegistry/templates/about.html
{% extends "base.html" %}
{% block content %}
  <div class = "about">
    <h2>Introduction</h2>
    <p>We here at Pet Lives Matter believe that pet lives matter. It may seem
      like unneccesary repetition, but it is true. Your furry family matters, at
      least as much as actual people. Some would say even more so, but we are
      are not legally allowed to say that anymore. Pets are important, as they
      don't hurt people and in fact cannot speak. Sometimes it says more to say
      nothing than it does to say something. That's why we love pets, they have
      to listen to you. And they will eat whatever you give them, more so than
      any human child would.
   </p>
   <p>However, one common issue with pets is that they cannot use the internet
      or social media. So if they go missing and lose their way, it can be
      quite difficult for them to come home. You used to have to rely on the
      kindness of strangers, which is kind of strange. Not only that, but you
      would likely have to print out many flyers and posters, and go through
      the dilemma of putting them up around town. If only there was a virtual
      alternative. Well, thanks to out generous clients at the Auckland council,
      there is!
    </p>

  </div>
  <div class = "contact">
    <h2>Contact Us:</h2>
      <h4>Email: </h4><p>info@PetLivesMatter.co.nz</p>
      <h4>Phone: </h4><p>0800 555 PETS</p>
      <h4>Address: </h4><p>28 Kells Avenue, Whanganui, Manawatu-Wanganui</p>
  </div>

  <h2>Legal:</h2>
  <p>We do take your personal information but we promise not to share it to
    anyone who shouldn't have it.
 </p>


{% endblock %}

PetLivesMatter/PetRegistry/templates/base.html
{% load static %}
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Home | Pet Lives Matter</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon">
    <link rel="icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    {% load static %}

    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" media="all">


<header>
  <div class="header">
    <div class="main-head-wrap inner-wrap clearfix">
      <div id="hero-image-div">
        <div id="header-logo-image">
          <img src="{% static 'images/logo.png' %}" alt="Pets Lives Matter">
        </div>
        <div id = "header-banner-image">
          <img src="{% static 'images/header.jpg' %}" alt="Pet Lives Matter">
          <div id="header-text">
            <h1 id="site-title">
              Pets Lives Matter
            </h1>
          </div>
        </div>
      </div>
    </div>
</header>
    </head>
    <body class="wide">

      <div class="container-fluid">
        <div class="row">
            <div class="col-sm-2">
              <ul class="sidebar-nav">
                <br><br><br>
                <li><a href="{% url 'home' %}">Home</a></li>
                <li><a href="{% url 'missing_pets' %}">Missing Pets</a></li>
                <li><a href="{% url 'about' %}">About Us</a></li>
                <li><a href="{% url 'donate' %}">Donate</a></li>
              </ul>
              {% if user.is_authenticated %}
                <li>User: {{ user.get_username }}</li>
                <li><a href="{% url 'my_pets' %}">My Pets</a></li>
                <li><a href="{% url 'user_detail' %}">My Account</a></li>
                <li><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>
              {% else %}
                <li><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>
                <ul>or</ul>
                <li><a href="{% url 'signup'%}?next={{request.path}}">Register</a></li>
              {% endif %}
            </div>
        <div id="page" class="hfeed site">

            <div class="main-wrapper">
                <div class="single-page clearfix">
                    <div class="inner-wrap">
                        <hr>
                        <div>
                          {% block content %}
                          {% endblock %}
                              </div>
                        </div>
                    </div>
                </div>
            </div>
            <footer id="colophon">
              <div class="footer-nav">
                <ul><a href="{% url 'about' %}">Privacy Policy</a></ul>
                <ul><a href="{% url 'about' %}">Terms and Conditions</a></ul>
                <ul><a href="{% url 'about' %}">Copyright</a></ul>
            </div>
                <div class="inner-wrap">
                    <ul class="contact-us-class"><a href="">Contact Us</a></ul>
                    <ul class="contact-us-class">Phone Number: 0800 555 PETS</ul>
                    <ul class="contact-us-class">Email Address: info@PetLivesMatter.co.nz</ul>
                </div>
            <div id="footer-logos">
              <p><a href=""><img src="{% static 'images/AucklandCouncil_logo.png' %}" alt="Auckland Council"></a>
              <a href=""><img src="{% static 'images/SPCA_logo.png' %}" alt="Pets Lives Matter"></a>
              <a href=""><img src="{% static 'images/LocalCommunity_logo.png' %}" alt="Pets Lives Matter"></a></p>
            </div>
            </footer>
        </div>
      </div>
    </body>
</html>

PetLivesMatter/PetRegistry/templates/donate.html
{% extends "base.html" %}
{% block content %}
{% load static %}
  <div class = "about">
    <h2>Introduction</h2>
    <p>While this is a free service, we still have operating costs, so any money
      is appreciated! It goes a long way to keeping us going to help build
      communities around having the same kind of fluffy housemate. Not only can
      you donate to us, but you can also donate to the RSPCA to let them do the
      real hard work.
     </p>


  </div>
  <div class = "contact">
    <h2>Donate:</h2>
      <a href="https://www.spca.nz/donate/donate-now"><img src="{% static 'images/SPCA_logo.png' %}"  alt="SPCA"></a>
  </div>


{% endblock %}

PetLivesMatter/PetRegistry/templates/home.html
{% extends "base.html" %}
{% block content %}
  <div class = "intro">
    <h2>Introduction</h2>
    <p><b>Welcome to Pets Lives Matter!</b><br>
      Has your pet gone missing? Are you afraid of your beloved pet running away
      and not being able to find it?<br>
      Pets Lives Matter allows you and fellow pet enthusiasts in your neighbour
      hood register your pets so if they decide to go missing you can alert your
      local community, making it easier for someone to identify it. If someone
      finds a lost animal they can easily identify it through our missing pet
      registry.<br>
       </p>
     <p><b>How do you use Pets Lives Matter? </b><br>
  <b>Step 1: </b> Register yourself and go through the verification steps<br>
  <b>Step 2: </b> Register your pets with the applicable details<br>
  <b>Step 3: </b> If your pet has gone missing please go to its profile and
   label it as missing<br>
  <b>What happens now? </b><br>
  An alert will be sent out to other users in your community to look out for it.
   We are also linked to the SPCA so they will get a notice as well. If your pet
    is found by the SPCA an alert will be sent to you to contact them. <br>
  <b>I have found a lost pet? How do I identify it? </b><br>
  Please go to the missing pet page and fill in the filters,
  pets matching the description will be shown. <br>
  There will be a contact family button, please press this and enter your
   details. An alert will be sent to the family to contact you. <br>
  </p>
  </div>
  <div class = "tg-one-third">
    <h3>Testimony</h3>
    <p>
      <i>"I've always struggled keeping track of my cats. They
      said that 32 was too many. Now I can keep up with them all
     and keep track of them."</i>
     -Hannah Wyoming, 2020
    </p>
  </div>
  <div class = "tg-one-third">
    <h3>Testimony</h3>
    <p>
      <i>"I used to always kidnap peoples pets and let them loose randomly
        across the neighbourhood. This had made my life very difficult.
        Thanks a bunch Pet Lives Matter..."</i>
     -Upton O.Goode, 2020
    </p>
  </div>
  <div class = "tg-one-third-last">
    <h3>Testimony</h3>
    <p>
      <i>"I found my dog."</i>
     -Bob McGeal, 2020
    </p>
  </div>


{% endblock %}

PetLivesMatter/PetRegistry/templates/missing_pets.html
{% extends "base.html" %}
{% block content %}

<!-- <div class = "missingpets">
  <form action="" method="get" class="missing_pets_form">
  <label for="category">Missing Pet Filters</label>
  <select id="category" class="form-control" name="category">
    <option selected>Choose...</option>
    {% for Pet in categories %}
    <option value="{{species}}"> {{species}} </option>
    <option value="{{sex}}"> {{sex}} </option>
    <option value="{{colour}}"> {{colour}} </option>
    <option value="{{eye_colour}}"> {{eye_colour}} </option>
    {% endfor %}
  </select>
    <input type="submit" value="search" class="">
  </form>


</div> -->

<!-- <form class="row">
    {{ form.search }}
    {{ form.filter_field }}
    <input type="submit" class="btn btn-default" value="Search">
</form>
--->

<h2>Missing Pets:</h2>

{% for pet in pet_list %}
  {% if pet.missing == True %}
    <div class="pet">
      <div>
        <img class="pet-detail-image" src="{{ pet.imagefile.url }}" />
        <h1>{{pet.pet_name|capfirst}} </h1>
        <br><br>
        <p><b>Species:</b> {{ pet.species}} </p>
        <p><b>Body Colour:</b> {{ pet.colour}} </p>
        <p><b>Age:</b> {{ pet.age}} </p>
        <p><b>Sex:</b> {{ pet.sex}} </p>
        <p><b>Eye Colour:</b> {{ pet.eye_colour}} </p>
        <p><b>Markings:</b> {{ pet.markings}} </p>
      <hr>

    </div>


  {% endif %}
{% endfor %}


{% endblock %}

PetLivesMatter/PetRegistry/templates/my_pets.html
{% extends "base.html" %}

{% block content %}
  {% if user.is_authenticated %}

    <h2>My Pets:</h2>

    {% for pet in pet_list %}
      {% if pet.owner.get_username == user.get_username %}
        <div class="pet">
          <a href="{% url 'pet_detail' pet.id %}">
            <img class="pet-list-image" src="{{ pet.imagefile.url }}" />
            <h3>{{pet.pet_name | capfirst}}</h3>
          </a>
          <p>{{pet.colour}} {{pet.species}}</p>
          <hr>

        </div>


      {% endif %}
    {% endfor %}
    <h3><a href="{% url 'pet_register' %}">Register a pet</a></h3>
  {% else %}
    <p>Log in to see your pets!!!</p>
{% endif %}
{% endblock %}

PetLivesMatter/PetRegistry/templates/pet_detail.html
{% extends "base.html" %}
{% block content %}
  {% if user.is_authenticated and user.get_username == pet.owner.get_username %}
    <div>
      <img class="pet-detail-image" src="{{ pet.imagefile.url }}" />
      <h1>{{pet.pet_name|capfirst}} </h1>
      <br><br>
      <p><b>Species:</b> {{ pet.species}} </p>
      <p><b>Body Colour:</b> {{ pet.colour}} </p>
      <p><b>Age:</b> {{ pet.age}} </p>
      <p><b>Sex:</b> {{ pet.sex}} </p>
      <p><b>Eye Colour:</b> {{ pet.eye_colour}} </p>
      <p><b>Markings:</b> {{ pet.markings}} </p>
      {% if pet.missing == True %}
        <p><b>Missing:</b> YES </p>
      {% else %}
        <p><b>Missing:</b> NO </p>
      {% endif %}

      <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">Change Missing Status</button>
      </form>
      <br>
    </div>
  {% else %}
    <p>Log in to see your pets!!!</p>
  {% endif %}
{% endblock %}

PetLivesMatter/PetRegistry/templates/pet_register.html
{% extends "base.html" %}

{% block content %}
  {% if user.is_authenticated %}

    <h2>Pet Regstration Form</h2>
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {% for field in form %}
        <div>
          {{ field.label_tag }}<br>
          {{ field }}
          {% if field.help_text %}
            <small style="color: grey">{{ field.help_text }}</small>
          {% endif %}
          {% for error in field.errors %}
            <p style="color: red">{{ error }}</p>
          {% endfor %}
        </div>
      {% endfor %}
      <button type="submit">Register Pet</button>
    </form>

  {% else %}
    <p>Log in to register your pets!!!</p>
  {% endif %}
{% endblock %}

PetLivesMatter/PetRegistry/templates/signup.html
{% extends "base.html" %}

{% block content %}

  <h2>Sign up Form</h2>
  <form method="post">
    {% csrf_token %}
    {% for field in form %}
      <p>
      {{ field.label_tag }}<br>
      {{ field }}
      {% if field.help_text %}
        <small style="color: grey">{{ field.help_text }}</small>
      {% endif %}
      {% for error in field.errors %}
        <p> style="color: red">{{ error }}</p>
      {% endfor %}
      </p>
    {% endfor %}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}